version: 1.0.{build}

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    CMAKE_GENERATOR: Unix Makefiles
    CXX_COMPILER: g++

  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    CMAKE_GENERATOR: Unix Makefiles
    CXX_COMPILER: clang++

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: Visual Studio 14 2015

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_GENERATOR: Visual Studio 14 2015 Win64

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: Visual Studio 15 2017

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64

before_build:
  - cmd: cmake . -G "%CMAKE_GENERATOR%" -DMEM_TEST=ON -DCMAKE_BUILD_TYPE=Release
  - sh: cmake . -G "$CMAKE_GENERATOR" -DMEM_TEST=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER="$CXX_COMPILER"

build_script:
  - cmake --build . --config Release

test_script:
  - ctest -V -C Release
